version: '3.5'

services:
  app_prod:
    container_name: nestjs_vendas_api
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - /home/node/app/dist
      - /home/node/app/node_modules

