name: nest

on:
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Build the application
        run: |
          npm install
          npm run build

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.0
        with:
            name: api_nest
            path: ./dist

  docker:
    needs: build
    uses: ./.github/workflows/docker.yml
    secrets: inherit

  deploy_ec2:
    needs: build
    uses: ./.github/workflows/ec2.yml
    secrets: inherit
